// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtgvWn0-0OLnuZ1VulKyKOxUyrWBxZyQw',
    appId: '1:1082553976783:web:bb429679234dc5edfe74ba',
    messagingSenderId: '1082553976783',
    projectId: 'mood-journal-6b7dc',
    authDomain: 'mood-journal-6b7dc.firebaseapp.com',
    storageBucket: 'mood-journal-6b7dc.firebasestorage.app',
    measurementId: 'G-PGS20M94BP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHbLKEKxRqykocrihSjgS2nW1X4rQxDM8',
    appId: '1:1082553976783:android:33a53b776ccdeaadfe74ba',
    messagingSenderId: '1082553976783',
    projectId: 'mood-journal-6b7dc',
    storageBucket: 'mood-journal-6b7dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBfVkez9ZxucnxRO9AXWkJIE8r9YP0gjA',
    appId: '1:1082553976783:ios:3713536d7c25df91fe74ba',
    messagingSenderId: '1082553976783',
    projectId: 'mood-journal-6b7dc',
    storageBucket: 'mood-journal-6b7dc.firebasestorage.app',
    iosBundleId: 'com.example.uasC14220127',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBfVkez9ZxucnxRO9AXWkJIE8r9YP0gjA',
    appId: '1:1082553976783:ios:3713536d7c25df91fe74ba',
    messagingSenderId: '1082553976783',
    projectId: 'mood-journal-6b7dc',
    storageBucket: 'mood-journal-6b7dc.firebasestorage.app',
    iosBundleId: 'com.example.uasC14220127',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtgvWn0-0OLnuZ1VulKyKOxUyrWBxZyQw',
    appId: '1:1082553976783:web:1c056310d31e8425fe74ba',
    messagingSenderId: '1082553976783',
    projectId: 'mood-journal-6b7dc',
    authDomain: 'mood-journal-6b7dc.firebaseapp.com',
    storageBucket: 'mood-journal-6b7dc.firebasestorage.app',
    measurementId: 'G-N98F5G0JH8',
  );
}
